### ISSUE TITLE
Mailtrain Roadmap

### ISSUE THREAD

**Issue by andris9** [Mailtrain-org/mailtrain#12]
This is a meta-issue to track new features
- [ ] Handlebars support in addition to normal HTML. This would enable to use more complex logic
- [ ] Prefetch linked images and embed as attachments
- [ ] Campaign specific merge tags. Maybe import from a CSV file? Would make it possible to provide custom fields like coupon codes, pdf links etc.

---
- [x] Upgrade template editor. Mosaico seems like a great option (#10)
- [x] Bounce detection by grepping Postfix logs
- [x] Continous campaigns – currently once all subscribers have received a message the campaign is ended. It should be possible to keep it running, so if new subscribers appear then they would get the same message automatically. Also required for RSS campaigns, drip campaigns etc. [docs](https://github.com/andris9/mailtrain/wiki/Automation-in-Mailtrain)
- [x] Relative datetime segmentation rules – it should be possible to create rules like "1 day after signup"
- [x] Message preview before sending out the campaign [docs](https://github.com/andris9/mailtrain/wiki/Previewing-campaigns)
- [x] RSS campaigns – every new entry in a RSS file should create a new campaign and send the contents of the RSS entry as the message to a selected list [docs](https://github.com/andris9/mailtrain/wiki/RSS-Campaigns)
- [x] Scheduled sending (#23) [docs](https://github.com/andris9/mailtrain/wiki/Scheduling-Send-time)
- [x] Additional SMTP configuration, for example to allow self-signed certificates (#7)
- [x] Message source from an URL – instead of editing message template in Mailtrain it should be possible to fetch it from a provided URL (#8)
- [x] GPG encryption – users should be able to upload their GPG key as part of their profile and if such key is set then all messages sent to this user should be GPG encrypted [docs](https://github.com/andris9/mailtrain/wiki/Adding-GPG-encryption-option-to-a-list)
- [x] API access [docs](https://github.com/andris9/mailtrain/wiki/Using-API)
- [x] Disable tracking features for campaigns. If tracking is disabled before sending a campaign, tracking links are not used. If tracking is disabled after sending the campaign, redirects keep working but tracking information is not stored to db
- [x] Custom attachments

**Comment by vhpoet** [comment]
Any updates on the "disable tracking" thing?

**Comment by andris9** [comment]
@vhpoet fixed in v1.18.0. Campaigns have a new configuration option "disable tracking". This setting can be toggled any time. If tracking is disabled while sending a message, no tracking links are inserted into the message. If tracking was not disabled in send time but was disabled later, the message contains tracking links but this information is not used (eg. the redirection link redirects as intended but the redirect counter is not incremented)

**Comment by pastullo** [comment]
hey @andris9, loving Mailtrain! I started using it and it really is great!

Maybe not the right place but a great quick feature that i really feel is missing is a "Quick Preview" that actually sends the message to any email you type in.
So ideally there would be a "Test Send this Campaign" input box which would let you type in any email (ideally also comma separated).

Previewing an email in your inbox is muuuuuch more important than previewing the HTML only!

**Comment by andris9** [comment]
@pastullo what you can do for now is to create 2 lists, one would be the actual list and the other would be the test list. When you create a new campaign or want to test one, you could set the test list as the recipients. Then you could send the campaign to this test list and if everything looks fine, you could first reset the campaign state and then edit the campaign to change the list from test list to production list

**Comment by pastullo** [comment]
yes @andris9 that's what i am doing at the moment, but it's obviously not very sustainable. 
Continually testing a campaign in your inbox is key. I have seen newsletters being test sent several times before being approved. Definitely one of the top missing feature here!

**Comment by artf** [comment]
Hi @andris9, about the template editor, I'd like to suggest you GrapesJS as an option.
Check this demo and let me know if you're interested http://grapesjs.com/demo-newsletter-editor.html

**Comment by andris9** [comment]
@artf GrapeJS looks really great! Does it take HTML as an input and also outputs HTML or does it needs something special? I mean, how easy it would be to integrate into an existing solution like Mailtrain? Also, is this something that needs to be opened in a separate window or would it be possible to embed the editor into the Mailtrain layout?

**Comment by artf** [comment]
> Does it take HTML as an input and also outputs HTML or does it needs something special?

Absolutely not, using also [grapesjs-preset-newsletter](https://github.com/artf/grapesjs-preset-newsletter) it'll be even easier:

```html
 <!-- Template starts inside  #myeditor-->
<div id="myeditor">
  <table>Template data</table>
  <style>/* some css here */</style>
</div>

<script>
var gjs = grapesjs.init({
  container : '#myeditor',
  //with this option you'll grab the template from the container
  fromElement: true,
})

// Generally, to get HTML and CSS with GrapesJS you do this
var html = gjs.getHtml();
var css = gjs.getCss();

// But 'grapesjs-preset-newsletter' adds a command which outputs inlined CSS
var htmlWithCss = gjs.runCommand('gjs-get-inlined-html');
</script>
```

> Also, is this something that needs to be opened in a separate window or would it be possible to embed the editor into the Mailtrain layout?

No, it's enough set the container and its dimension:

```html
<div id="myeditor" style="height:500px; width 100%">...</div>
```

> How easy it would be to integrate into an existing solution like Mailtrain?

To be honest, I don't know, but I think it's not gonna be so hard :)

I'd suggest you check the [API Reference](https://github.com/artf/grapesjs/wiki/API-Reference) and the [newsletter demo](https://github.com/artf/grapesjs-preset-newsletter/blob/master/index.html) (I think itself it could be a good start for you) but, in any case, I'll be always available to help you with the integration

For bugs don't hesitate to open issues on the repo and for any other question, you can reach me here: artur.catch at hotmail.it

**Comment by andris9** [comment]
Seems awesome! I was able to have GrapeJS running in a div which is exactly what is needed.

**Comment by artf** [comment]
@andris9 awesome :)

**Comment by forgeOneHQ** [comment]
I am closing this. We can have a discussion on slack for this.

https://mailtrainorg.slack.com
