### ISSUE TITLE
Mailtrain 2 beta roadmap

### ISSUE THREAD

**Issue by bures** [Mailtrain-org/mailtrain#410]
This is a list of bigger tasks which are to be done for the Mailtrain 2 beta. 

### General

- [x] Deletion of dependent entities 

### Lists

- [x] CVS Import with List update support. List update support means (1) to remember the mapping between CSV and fields, and (2) ability to select which fields are to be updated if missing.

- [x] CSV Export

### Templates

- [x] Selectable Mosaico templates in Mosaico-based template editor

- [x] GrapeJS-based template editor + GrapeJS MJML plugin

- [x] MJML-based template editor

- [x] Test email and HTML preview functionality in template editors

### Mail delivery

- [x] Mail configuration as a shareable entity (with all CUD functionality)

- [x] Port VERP server

- [x] Port mail delivery to await/async style and to use new mail configurations

### Campaigns

- [x] Port/redo all campaigns

- [x] RSS and triggered campaigns

- [x] Stats for a campaign

### Reports

- [x] Check if reports still work after all the changes so far. They have already been ported, but they came the very first, so it's hard to say if they still work.

### Testing

- [ ] Fix/update API tests

### For later (not for beta)

- Automatic list integration - i.e. to create/update a list based on other lists. This is needed when there are multiple persons each maintaining their own lists and if there should be the ability to deliver to all the lists at once.

- API for creating and sending out a campaign 

- MJML-based Mosaico Templates

**Comment by rrooij** [comment]
What about AB/testing for the 2.0 beta, since it is been requested pretty often (#354, #95)? Or is that out of scope?

**Comment by bures** [comment]
Definitely not out of scope. It's just that I wanted to have some "minimal" feature set start testing the new version. Since it has been a complete rewrite of existing Mailtrain, it seemed easier to have kind of "enhanced existing state" as the primary goal.

My goal is to roll out a working version that uses the new UI and new server internals, such that others can extend it with additional features, like A/B testing.

**Comment by JWDT** [comment]
That all looks awesome!

I think I saw somewhere that V2 would support multiple users/brands, is that going to be the case from the beta?

Looking forward to testing ASAP. :smile:

**Comment by bures** [comment]
:-D Not so ASAP. :-) I estimate I might have something during summer at earliest. 

In any case, support for multiple users is already implemented.

**Comment by saschafoerster** [comment]
Looking forward to it! Keep on rolling! If money can help, please open a place, where we can support the development.

**Comment by bures** [comment]
Thanks @saschafoerster . I think more than money, time is the critical resource. :-)

**Comment by bures** [comment]
Mailtrain v2 beta is now available. Please see #505 and continue your comments there. Thanks.

**Comment by harshpatel-mainvps** [comment]
Hello, 

when I try to setup Mailtrain by follow this link in [https://github.com/Mailtrain-org/mailtrain](url) in centos 7 on public website.
script was execute successfully without any error and httpd and Mailtrain services also started without  any any error. 
but when I try to open link in any browser it give an error like 
" Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later."
![github](https://user-images.githubusercontent.com/95604023/144791640-d32b5e97-e14f-4de2-b209-bb4b7936340c.png)

Please Help me to fix  this issue"

Thanks
